<?$APPLICATION->IncludeComponent(
	"aspro:tabs.allcorp3", 
	".default", 
	array(
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DETAIL_URL" => "",
		"FILTER_NAME" => "arFilterCatalog",
		"HIT_PROP" => "HIT",
		"IBLOCK_ID" => "",
		"IBLOCK_TYPE" => "aspro_allcorp3_catalog",
		"PAGE_ELEMENT_COUNT" => "FROM_THEME",
		"PARENT_SECTION" => "",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "SHOW_ON_INDEX_PAGE",
			2 => "STATUS",
			3 => "ARTICLE",
			4 => "PRICE",
			5 => "FORM_ORDER",
			6 => "PRICEOLD",
			7 => "ECONOMY",
			8 => "DATE_COUNTER",
			9 => "HIT",
			10 => "BRAND",
			11 => "RECOMMEND",
			12 => "",
		),
		"ELEMENT_SORT_FIELD" => "SORT",
		"ELEMENT_SORT_FIELD2" => "ID",
		"ELEMENT_SORT_ORDER" => "ASC",
		"ELEMENT_SORT_ORDER2" => "ASC",
		"TITLE" => "Продукция",
		"COMPONENT_TEMPLATE" => ".default",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_PICTURE",
			3 => "",
		),
		"ELEMENTS_TABLE_TYPE_VIEW" => "FROM_MODULE",
		"SHOW_SECTION" => "N",
		"COUNT_IN_LINE" => "4",
		"RIGHT_TITLE" => "Каталог",
		"RIGHT_LINK" => "product/",
		"SHOW_DISCOUNT_TIME" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"SHOW_PREVIEW_TEXT" => "N",
		"SHOW_DISCOUNT_PRICE" => "Y",
		"SHOW_GALLERY" => "Y",
		"ADD_PICT_PROP" => "PHOTOS",
		"MAX_GALLERY_ITEMS" => "5",
		"SUBTITLE" => "Каталог",
		"SKU_IBLOCK_ID" => "42",
		"SKU_PROPERTY_CODE" => array(
		),
		"SKU_TREE_PROPS" => array(
		),
		"SKU_SORT_FIELD" => "name",
		"SKU_SORT_ORDER" => "asc",
		"SKU_SORT_FIELD2" => "sort",
		"SKU_SORT_ORDER2" => "asc",
		"TYPE_TEMPLATE" => "catalog_block",
		"NARROW" => "FROM_THEME",
		"ITEMS_OFFSET" => "FROM_THEME",
		"TEXT_CENTER" => "FROM_THEME",
		"IMG_CORNER" => "FROM_THEME",
		"ELEMENT_IN_ROW" => "FROM_THEME",
		"COUNT_ROWS" => "FROM_THEME"
	),
	false
);?>